# `0 = Black  |  `1 = DarkGray
# `2 = GRAY   |  `w = White
# `r = Red    |  `R = DarkRed
# `y = YELLOW |  `Y = Gold
# `g = Green  |  `G = DarkGreen
# `c = Cyan   |  `C = DarkCyan
# `b = Blue   |  `B = DarkBlue
# `p = Purple |  `P = DarkPurple
# ------------------------------------------
# interval(MINUTES) - Interval between saves
# SilentMode - Operate in SilentMode (No Broadcasts/Console logs)
# ServerBroadcast - Broadcast a message to the server whenever data is autosaved
# AdminOnlyBroadcast - Broadcast a message only to those with Autosave.broadcast permission
# BroadcastEachWorld - Broadcast a confirmation of each world as it is saved
# AutoSaveMessage - Message to broadcast on AutoSave
# ------------------------------------------
interval: 30
Broadcast:
  SilentMode: false
  ConsoleLogging: true
  BroadcastEachWorld: false
  ServerBroadcast: true
  AdminOnlyBroadcast: false
  AutoSaveMessage: '`2[RD-AutoSave] `ySaving Worlds & Player Data...'
